use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'http://bj.gitlab.cnlive.com/ios-team/CNLiveRepos.git'
platform :ios, '9.0'

target 'CNLiveQrCodeModule_Example' do
  pod 'CNLiveQrCodeModule', :path => '../'
  
  target 'CNLiveQrCodeModule_Tests' do
    inherit! :search_paths
    
  end
end
